### ISSUE TITLE
Template not showing up

### ISSUE THREAD

**Issue by richbryant** [SQL-MisterMagoo/BlazorTwins#2]
Great idea, would definitely improve my life, installed the VSIX but no template shows in the VS2019 list.

Have I done it wrong?

**Comment by SQL-MisterMagoo** [comment]
It should show up if you type blazor in the search, like this:

![image](https://user-images.githubusercontent.com/11338430/59231313-24511080-8bd8-11e9-9081-15cad75ed2ce.png)

If not, try checking if it shows up in your extensions

![image](https://user-images.githubusercontent.com/11338430/59231397-6da16000-8bd8-11e9-8828-aebf5b10412f.png)

**Comment by richbryant** [comment]
I'm getting this

![blazortwins](https://user-images.githubusercontent.com/2277883/59231617-4303d700-8bd9-11e9-8098-d3077166c478.PNG)

 with this

![extensions](https://user-images.githubusercontent.com/2277883/59231633-5151f300-8bd9-11e9-826f-5d4abcc4d281.PNG)

**Comment by richbryant** [comment]
Wait!

Okay, that was weird.  I gave it one last try, got nothing, hit "Clear search filter" and suddenly there it was.

How odd.

**Comment by SQL-MisterMagoo** [comment]
Cool, at least you found it in the end - I see you had a filter by C# enabled - I'll see if I can find out how to add that tag to it, thanks for letting me know!

**Comment by SQL-MisterMagoo** [comment]
I have added the C#, Windows, Linux and Web tags now.
